name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build & push Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mega001
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t mega001/flaskapp:latest .

      - name: Push image
        run: docker push mega001/flaskapp:latest

      # Simple deployment test
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 300s
          command_timeout: 20m
          script: |
            echo "=== Starting deployment ==="
            whoami
            pwd
            
            # Ensure Docker is running
            sudo systemctl start docker
            
            # Stop existing container if running
            sudo docker stop flaskapp 2>/dev/null || echo "No container to stop"
            sudo docker rm flaskapp 2>/dev/null || echo "No container to remove"
            
            # Pull image with progress
            echo "Pulling image..."
            sudo docker pull mega001/flaskapp:latest
            
            # Create directories
            mkdir -p /home/ec2-user/data /home/ec2-user/uploads
            
            # Run container
            echo "Starting container..."
            sudo docker run -d \
              --name flaskapp \
              -p 8080:5003 \
              -e FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY }}" \
              -v /home/ec2-user/data:/app/data \
              -v /home/ec2-user/uploads:/app/static/uploads \
              --restart unless-stopped \
              mega001/flaskapp:latest
            
            # Check status
            sleep 10
            echo "=== Container status ==="
            sudo docker ps -a | grep flaskapp
            
            if sudo docker ps | grep flaskapp; then
              echo "✅ SUCCESS: Container is running!"
              echo "🌐 App accessible at: http://$(curl -s ifconfig.me):8080"
            else
              echo "❌ ERROR: Container not running"
              sudo docker logs flaskapp
              exit 1
            fi