name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build & push Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mega001
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t mega001/flaskapp:latest .

      - name: Push image
        run: docker push mega001/flaskapp:latest

      # Deploy (assuming Docker is already installed)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 5m
          script: |
            echo "Starting deployment..."
            
            # Create directories
            mkdir -p /home/ec2-user/data /home/ec2-user/uploads
            
            # Stop existing container
            docker stop flaskapp 2>/dev/null || echo "No existing container to stop"
            docker rm flaskapp 2>/dev/null || echo "No existing container to remove"
            
            # Pull latest image
            echo "Pulling Docker image..."
            docker pull mega001/flaskapp:latest
            
            # Run new container
            echo "Starting new container..."
            docker run -d \
              --name flaskapp \
              -p 8080:5003 \
              -e FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY }}" \
              -v /home/ec2-user/data:/app/data \
              -v /home/ec2-user/uploads:/app/static/uploads \
              --restart unless-stopped \
              mega001/flaskapp:latest
            
            # Verify
            sleep 10
            if docker ps | grep flaskapp; then
              echo "SUCCESS: Container is running!"
              echo "App accessible at: http://$(curl -s ifconfig.me):8080"
            else
              echo "ERROR: Container failed to start"
              docker logs flaskapp
              exit 1
            fi