name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build & push Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mega001
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t mega001/flaskapp:latest .

      - name: Push image
        run: docker push mega001/flaskapp:latest

      # Test SSH connection first
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "SSH connection successful!"
            whoami
            pwd
            docker --version

      # Deploy on EC2 (only if SSH test passes)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/data /home/ubuntu/uploads
            docker pull mega001/flaskapp:latest
            docker stop flaskapp || true
            docker rm flaskapp || true
            docker run -d --name flaskapp -p 8080:5003 -e FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY }}" -v /home/ubuntu/data:/app/data -v /home/ubuntu/uploads:/app/static/uploads --restart unless-stopped mega001/flaskapp:latest
            sleep 5
            docker ps | grep flaskapp