name: Debug SSH Connection

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        run: |
          # Create SSH directory and key file
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          
          # Show key info (first and last lines only for security)
          echo "Key file info:"
          head -1 ~/.ssh/ec2_key
          echo "..."
          tail -1 ~/.ssh/ec2_key
          
          # Test SSH connection
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          ssh -v -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no -o ConnectTimeout=10 ubuntu@${{ secrets.EC2_HOST }} "whoami" || echo "SSH failed"
          
          # Cleanup
          rm -f ~/.ssh/ec2_key