name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build & push Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mega001
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t mega001/flaskapp:latest .

      - name: Push image
        run: docker push mega001/flaskapp:latest

      # Deploy using native SSH
      - name: Deploy to EC2
        run: |
          # Create SSH key file
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          
          # Add EC2 host to known hosts
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
          # Deploy via SSH
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            echo "Starting deployment..."
            
            # Create directories
            mkdir -p /home/ubuntu/data /home/ubuntu/uploads
            echo "Directories created"
            
            # Pull latest image
            echo "Pulling Docker image..."
            docker pull mega001/flaskapp:latest
            echo "Image pulled successfully"
            
            # Stop existing container
            echo "Stopping existing container..."
            docker stop flaskapp 2>/dev/null || echo "No existing container to stop"
            docker rm flaskapp 2>/dev/null || echo "No existing container to remove"
            
            # Run new container
            echo "Starting new container..."
            docker run -d \
              --name flaskapp \
              -p 8080:5003 \
              -e FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY }}" \
              -v /home/ubuntu/data:/app/data \
              -v /home/ubuntu/uploads:/app/static/uploads \
              --restart unless-stopped \
              mega001/flaskapp:latest
            
            # Wait and verify
            echo "Waiting for container to start..."
            sleep 10
            
            if docker ps | grep flaskapp; then
              echo "SUCCESS: Container is running!"
              echo "Flask app is accessible on port 8080"
            else
              echo "ERROR: Container failed to start"
              docker logs flaskapp 2>/dev/null || echo "No logs available"
              exit 1
            fi
          EOF
          
          # Cleanup
          rm -f ~/.ssh/ec2_key